"""agent_aimodel_id

Revision ID: 02322111f175
Revises: 531e1589cb88
Create Date: 2026-04-05 00:06:35.468366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02322111f175'
down_revision = '531e1589cb88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Aggiungi colonna come nullable prima
    op.add_column('agents', sa.Column('aimodel_id', sa.Integer(), nullable=True))
    
    # Esegui la query per popolare i dati basandoti sul nome del modello testuale
    # (assumiamo che ci sia una corrispondenza tra agents.model e ai_models.name)
    op.execute("""
        UPDATE agents 
        SET aimodel_id = (SELECT id FROM ai_models WHERE ai_models.name = agents.model LIMIT 1)
    """)
    
    # Se non c'è corrispondenza o se agents.model è nullo, setta a un ID di fallback (es. 1 o un ID che sai esiste)
    # Esempio: op.execute("UPDATE agents SET aimodel_id = 1 WHERE aimodel_id IS NULL")
    op.execute("""
        UPDATE agents 
        SET aimodel_id = (SELECT id FROM ai_models ORDER BY id LIMIT 1)
        WHERE aimodel_id IS NULL
    """)

    # Ora rendi la colonna NOT NULL
    op.alter_column('agents', 'aimodel_id', nullable=False)

    op.create_foreign_key(None, 'agents', 'ai_models', ['aimodel_id'], ['id'])
    op.drop_column('agents', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    
    op.execute("""
        UPDATE agents
        SET model = (SELECT name FROM ai_models WHERE id = agents.aimodel_id LIMIT 1)
    """)
    
    op.alter_column('agents', 'model', nullable=False)
    
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'aimodel_id')
    # ### end Alembic commands ###