"""Add extra fields to ai_models: base_url, api_key, config

Revision ID: 531e1589cb88
Revises: e9f8fa1bba37
Create Date: 2026-04-04 12:32:19.948917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531e1589cb88'
down_revision = 'e9f8fa1bba37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('base_url', sa.String(length=500), nullable=True))
    op.add_column('ai_models', sa.Column('api_key', sa.String(length=200), nullable=True))
    op.add_column('ai_models', sa.Column('config', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_models', 'config')
    op.drop_column('ai_models', 'api_key')
    op.drop_column('ai_models', 'base_url')
    # ### end Alembic commands ###