"""Add agno tool fields to skills

Revision ID: 8f540f7782d1
Revises: bb498020c058
Create Date: 2026-04-06 10:53:24.445157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f540f7782d1'
down_revision = 'bb498020c058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('agno_tool_class', sa.String(length=200), nullable=True))
    op.add_column('skills', sa.Column('agno_tool_params', sa.Text(), nullable=True))
    op.alter_column('skills', 'category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skills', 'category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('skills', 'agno_tool_params')
    op.drop_column('skills', 'agno_tool_class')
    # ### end Alembic commands ###