"""add tenant_id to aimodel

Revision ID: bb498020c058
Revises: 02322111f175
Create Date: 2026-04-05 09:46:20.551964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb498020c058'
down_revision = '02322111f175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.execute("UPDATE ai_models SET tenant_id = 1 WHERE tenant_id IS NULL")
    op.alter_column('ai_models', 'tenant_id', nullable=False)
    
    op.drop_index('ix_ai_models_name', table_name='ai_models')
    op.create_index(op.f('ix_ai_models_name'), 'ai_models', ['name'], unique=False)
    op.create_unique_constraint('uq_aimodel_name_tenant', 'ai_models', ['name', 'tenant_id'])
    op.create_foreign_key('fk_aimodel_tenant_id', 'ai_models', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_aimodel_tenant_id', 'ai_models', type_='foreignkey')
    op.drop_constraint('uq_aimodel_name_tenant', 'ai_models', type_='unique')
    op.drop_index(op.f('ix_ai_models_name'), table_name='ai_models')
    op.create_index('ix_ai_models_name', 'ai_models', ['name'], unique=True)
    op.drop_column('ai_models', 'tenant_id')
    # ### end Alembic commands ###